x <- c(10, 20, 30, 40, 50)
y <- c(15, 25, 35, 45, 55)
cat("Data Vector x:", x, "\n")
cat("Data Vector y:", y, "\n")
mean_x <- mean(x)
mean_y <- mean(y)
cat("Mean of x:", mean_x, "\n")
cat("Mean of y:", mean_y, "\n")
var_x <- var(x)
var_y <- var(y)
cat("Variance of x:", var_x, "\n")
cat("Variance of y:", var_y, "\n")
sd_x <- sd(x)
sd_y <- sd(y)
cat("Standard Deviation of x:", sd_x, "\n")
cat("Standard Deviation of y:", sd_y, "\n")
covariance <- cov(x, y)
cat("Covariance between x and y:", covariance, "\n")
correlation <- cor(x, y)
cat("Correlation between x and y:", correlation, "\n")